version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: myapp
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app # เพื่อ debug
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      PYTHONPATH: /app
      MONGODB_URL: mongodb://mongo:27017
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-ai
      dockerfile: dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:


networks:
  app-network:
    driver: bridge
